/* 
https://www.iconfinder.com/icons/1243689/call_phone_icon
Creative Commons (Attribution 3.0 Unported);
https://www.iconfinder.com/Makoto_msk */

export const storeProducts = [
  {
    id: 1,
    title: "Acer Nitro 5 Intel Core i5-11th Generation",
    img: "img/product-1.png",
    price: 700,
    company: "ACER",
    info: "This laptop comes with the latest 11th Generation Intel Core i5-11300H processor giving the fastest single threaded laptop performance and higher performance.It also comes equipped with 4 GB of NVIDIA Geforce GTX 1650 so that you can enjoy an enhanced and seamless gaming experience.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Samsung S7",
    img: "img/product-2.png",
    price: 16,
    company: "SAMSUNG",
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Iphone 7",
    img: "img/product.png",
    price: 30,
    company: "apple",
    info: "APPLE Dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Portrait mode, and 4K video up to 60fps",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Apple MacBook Pro",
    img: "img/MACBOOK.png",
    price: 800,
    company: "APPLE",
    info: "Apple-designed M1 chip for a giant leap in CPU, GPU, and machine learning performance.Get more done with up to 20 hours of battery life, the longest ever in a Mac.8-core CPU delivers up to 2.8x faster performance to fly through workflows quicker than ever.8-core GPU with up to 5x faster graphics for graphics-intensive apps and games.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Apple MacBook Pro",
    img: "img/MACBOOK.png",
    price: 800,
    company: "APPLE",
    info: "Apple-designed M1 chip for a giant leap in CPU, GPU, and machine learning performance.Get more done with up to 20 hours of battery life, the longest ever in a Mac.8-core CPU delivers up to 2.8x faster performance to fly through workflows quicker than ever.8-core GPU with up to 5x faster graphics for graphics-intensive apps and games.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Apple iPad ",
    img: "img/IPAD.PNG",
    price: 200,
    company: "APPLE",
    info: "Gorgeous 25.91 cm (10.2-inch) Retina display.A12 Bionic chip with Neural Engine",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Apple iPhone 12 Pro (128GB) - Silver ",
    img: "img/IPHONE.png",
    price: 600,
    company: "APPLE",
    info: "Pro camera system with 12MP Ultra Wide, Wide and Telephoto cameras; 4x optical zoom range; Night mode, Deep Fusion, Smart HDR 3, Apple ProRAW, 4K Dolby Vision HDR recording.6.1-inch (15.5 cm diagonal) Super Retina XDR display.Ceramic Shield, tougher than any smartphone glass",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Google Pixel - Black",
  img: "img/product-1.png",
  price: 10,
  company: "google",
  info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0,
};
